{"created": "2020-12-04 19:03:12.202394", "duration": 0.8856322765350342, "exitcode": 0, "root": "group2", "summary": {"passed": 5, "xpassed": 1, "total": 6, "collected": 6}, "tests": [{"nodeid": "managements/test_user_management.py::test_create_auth_user[Testing an invalid email-invalid_email.com-error]", "outcome": "passed", "metadata": ""}, {"nodeid": "managements/test_user_management.py::test_create_auth_user[Testing an invalid email--error]", "outcome": "passed", "metadata": ""}, {"nodeid": "managements/test_user_management.py::test_create_user[valid user-success0]", "outcome": "passed", "metadata": ""}, {"nodeid": "managements/test_user_management.py::test_create_user[valid user-success1]", "outcome": "passed", "metadata": ""}, {"nodeid": "managements/test_user_management.py::test_create_user[invalid user-error]", "outcome": "passed", "metadata": ""}, {"nodeid": "managements/test_user_management.py::test_login", "lineno": 27, "outcome": "xpassed", "keywords": ["xfail", "test_login", "pytestmark", "group2", "managements/test_user_management.py"], "setup": {"duration": 0.00030689999999999884, "outcome": "passed"}, "call": {"duration": 0.00022839999999990646, "outcome": "passed"}, "teardown": {"duration": 0.00024930000000000785, "outcome": "passed"}}], "success": false}